name: Release
on:
  push:
    tags:
      - v*


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install atlassian-plugin-sdk
        run: |
          wget -nv https://packages.atlassian.com/api/gpg/key/public
          sudo apt-key add public
          sudo sh -c 'echo "deb https://packages.atlassian.com/atlassian-sdk-deb stable contrib" >> /etc/apt/sources.list'
          sudo apt-get -q -y install apt-transport-https
          sudo apt-get -q update
          sudo apt-get -q -y install atlassian-plugin-sdk

      - name: Build packages
        run: |
          atlas-package --batch-mode
          zip --junk-paths prism target/prism-*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./prism.zip
          asset_name: prism.zip
          asset_content_type: application/zip